site_name: GoElites Wiki
repo_url: https://github.com/y1n/GoElites.Wiki
pages:
- Accueil: index.md
- Principles:
    - Règles de la Communauté: CommunityPrinciples/CommunityGuidelines.md
    - Règles du Support: CommunityPrinciples/SupportGuidelines.md
- Pour démmarer:
    - Installer GoElites: GettingStarted/Installation.md
    - Fonctionnalités expliquées: GettingStarted/Features.md
    - Champions supportés: GettingStarted/SupportedChampions.md
    - FAQ: GettingStarted/FrequentlyAskedQuestions.md
- Dépanner:
    - Comment signaler un problème: Troubleshooting/TroubleshootingReportGuide.md
    - Support du Site: Troubleshooting/WebsiteTroubleshooting.md
    - Support de l'Application: Troubleshooting/ApplicationTroubleshooting.md
    
theme: readthedocs
